version: "3.7"
services:
  admin-api:
    image: conneqt/connector-admin-api:5.1.0.358
    environment:
      CONNECTOR_ADMIN_USERNAME: admin
      CONNECTOR_ADMIN_PASSWORD: password
      CONNECTOR_PROXY_LOADBALANCER_URL: http://proxy:8085
      CONNECTOR_PROXY_ACTUATOR_URL: http://proxy:8081
    ports:
      - 8082:8082
    volumes:
      - "./services.json:/etc/conneqt/connector/services.json"

  admin-ui:
    image: conneqt/connector-admin-ui:5.1.0.379
    environment:
      CONNECTOR_ADMIN_API_HOST: admin-api
      CONNECTOR_ADMIN_API_PORT: 8082
    ports:
      - 8443:443
    depends_on:
      - admin-api

  proxy:
    image: conneqt/connector-proxy:5.1.0.364
    ports:
      - 8085:8085
    volumes:
      - "./services.json:/etc/conneqt/connector/services.json"

  mysql:
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: connector
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./0_create.sql:/docker-entrypoint-initdb.d/0_create.sql
    ports:
      - 3306:3306
